import Footer from './components/footer/Footer'
import FixedEleComp from './components/public/FixedEleComp'
import HeaderComp from './components/header/HeaderComp'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <body>
        <HeaderComp/>
        {children}
        <Footer/>
        <FixedEleComp/>
      </body>
  )
}
