import '@/app/globals.css'
import '@/app/animation.css'
import Footer from './components/footer/Footer'
import FixedEleComp from './components/public/FixedEleComp'
import HeaderComp from './components/header/HeaderComp'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir='rtl'>
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;500;600;700;800;900;1000&display=swap" rel="stylesheet" />
      </head>
      <body>
        <HeaderComp/>
        {children}
        <Footer/>
        <FixedEleComp/>
      </body>
    </html>
  )
}
